# Tools.cmake

include(CSharpUtilities)

set(src_radiant_net 
	./engine/tools/radiant.net/bin
	./engine/tools/radiant.net/Editor.cs
	./engine/tools/radiant.net/filelist.txt
	./engine/tools/radiant.net/NativeAPI.cs
	./engine/tools/radiant.net/packages.config
	./engine/tools/radiant.net/RadiantHelpers.cs
	./engine/tools/radiant.net/Forms/CamWndDialog.cs
	./engine/tools/radiant.net/Forms/CamWndDialog.Designer.cs
	./engine/tools/radiant.net/Forms/CamWndDialog.resx
	./engine/tools/radiant.net/Forms/EntityCreateDialog.cs
	./engine/tools/radiant.net/Forms/EntityCreateDialog.Designer.cs
	./engine/tools/radiant.net/Forms/EntityCreateDialog.resx
	./engine/tools/radiant.net/Forms/EntitySelection.cs
	./engine/tools/radiant.net/Forms/EntitySelection.Designer.cs
	./engine/tools/radiant.net/Forms/EntitySelection.resx
	./engine/tools/radiant.net/Forms/InspectorDialog.cs
	./engine/tools/radiant.net/Forms/InspectorDialog.Designer.cs
	./engine/tools/radiant.net/Forms/InspectorDialog.resx
	./engine/tools/radiant.net/Forms/ProgressDialog.cs
	./engine/tools/radiant.net/Forms/ProgressDialog.Designer.cs
	./engine/tools/radiant.net/Forms/ProgressDialog.resx
	./engine/tools/radiant.net/Forms/XYWndDialog.cs
	./engine/tools/radiant.net/Forms/XYWndDialog.Designer.cs
	./engine/tools/radiant.net/Forms/XYWndDialog.resx
	./engine/tools/radiant.net/Properties/AssemblyInfo.cs
)

set(src_maya_import 
	./engine/MayaImport/maya_precompiled.cpp
	./engine/MayaImport/maya_main.cpp
)

set(src_tools
	./engine/tools/tools_precompiled.cpp
	./engine/tools/af/DialogAF.cpp
	./engine/tools/af/DialogAFBody.cpp
	./engine/tools/af/DialogAFConstraint.cpp
	./engine/tools/af/DialogAFConstraintBallAndSocket.cpp
	./engine/tools/af/DialogAFConstraintFixed.cpp
	./engine/tools/af/DialogAFConstraintHinge.cpp
	./engine/tools/af/DialogAFConstraintSlider.cpp
	./engine/tools/af/DialogAFConstraintSpring.cpp
	./engine/tools/af/DialogAFConstraintUniversal.cpp
	./engine/tools/af/DialogAFName.cpp
	./engine/tools/af/DialogAFProperties.cpp
	./engine/tools/af/DialogAFView.cpp
	./engine/tools/comafx/CDIB.cpp
	./engine/tools/comafx/CPathTreeCtrl.cpp
	./engine/tools/comafx/CSyntaxRichEditCtrl.cpp
	./engine/tools/comafx/DialogColorPicker.cpp
	./engine/tools/comafx/DialogGoToLine.cpp
	./engine/tools/comafx/DialogName.cpp
	./engine/tools/comafx/StdAfx.cpp
	./engine/tools/comafx/VectorCtl.cpp
	./engine/tools/common/AlphaPopup.cpp
	./engine/tools/common/ColorButton.cpp
	./engine/tools/common/MaskEdit.cpp
	./engine/tools/common/OpenFileDialog.cpp
	./engine/tools/common/PropertyGrid.cpp
	./engine/tools/common/RegistryOptions.cpp
	./engine/tools/common/RollupPanel.cpp
	./engine/tools/common/SpinButton.cpp
	./engine/tools/common/PropTree/PropTree.cpp
	./engine/tools/common/PropTree/PropTreeInfo.cpp
	./engine/tools/common/PropTree/PropTreeItem.cpp
	./engine/tools/common/PropTree/PropTreeItemButton.cpp
	./engine/tools/common/PropTree/PropTreeItemCheck.cpp
	./engine/tools/common/PropTree/PropTreeItemColor.cpp
	./engine/tools/common/PropTree/PropTreeItemCombo.cpp
	./engine/tools/common/PropTree/PropTreeItemEdit.cpp
	./engine/tools/common/PropTree/PropTreeItemEditButton.cpp
	./engine/tools/common/PropTree/PropTreeItemFileEdit.cpp
	./engine/tools/common/PropTree/PropTreeItemStatic.cpp
	./engine/tools/common/PropTree/PropTreeList.cpp
	./engine/tools/common/PropTree/PropTreeView.cpp
	./engine/tools/compilers/matbuild/matbuild.cpp
	./engine/tools/compilers/dmap/dmap.cpp
	./engine/tools/compilers/dmap/facebsp.cpp
	./engine/tools/compilers/dmap/gldraw.cpp
	./engine/tools/compilers/dmap/glfile.cpp
	./engine/tools/compilers/dmap/leakfile.cpp
	./engine/tools/compilers/dmap/map.cpp
	./engine/tools/compilers/dmap/optimize.cpp
	./engine/tools/compilers/dmap/optimize_gcc.cpp
	./engine/tools/compilers/dmap/output.cpp
	./engine/tools/compilers/dmap/portals.cpp
	./engine/tools/compilers/dmap/tritjunction.cpp
	./engine/tools/compilers/dmap/tritools.cpp
	./engine/tools/compilers/dmap/ubrush.cpp
	./engine/tools/compilers/dmap/usurface.cpp
	./engine/tools/compilers/megagen/MegaGen.cpp
	./engine/tools/compilers/megagen/MegaProject.cpp
	./engine/tools/compilers/megalight/MegaLight.cpp
	./engine/tools/compilers/renderbump/renderbump.cpp
	./engine/tools/compilers/renderprobes/renderprobes.cpp
	./engine/tools/decl/DialogDeclBrowser.cpp
	./engine/tools/decl/DialogDeclEditor.cpp
	./engine/tools/decl/DialogDeclNew.cpp
	./engine/tools/guied/GEApp.cpp
	./engine/tools/guied/GECheckInDlg.cpp
	./engine/tools/guied/GEDeleteModifier.cpp
	./engine/tools/guied/GEHideModifier.cpp
	./engine/tools/guied/GEInsertModifier.cpp
	./engine/tools/guied/GEItemPropsDlg.cpp
	./engine/tools/guied/GEItemScriptsDlg.cpp
	./engine/tools/guied/GEKeyValueModifier.cpp
	./engine/tools/guied/GEModifier.cpp
	./engine/tools/guied/GEModifierGroup.cpp
	./engine/tools/guied/GEModifierStack.cpp
	./engine/tools/guied/GEMoveModifier.cpp
	./engine/tools/guied/GENavigator.cpp
	./engine/tools/guied/GEOptions.cpp
	./engine/tools/guied/GEOptionsDlg.cpp
	./engine/tools/guied/GEProperties.cpp
	./engine/tools/guied/GEPropertyPage.cpp
	./engine/tools/guied/GESelectionMgr.cpp
	./engine/tools/guied/GESizeModifier.cpp
	./engine/tools/guied/GEStateModifier.cpp
	./engine/tools/guied/GEStatusBar.cpp
	./engine/tools/guied/GETransformer.cpp
	./engine/tools/guied/GEViewer.cpp
	./engine/tools/guied/GEWindowWrapper.cpp
	./engine/tools/guied/GEWorkspace.cpp
	./engine/tools/guied/GEWorkspaceFile.cpp
	./engine/tools/guied/GEZOrderModifier.cpp
	./engine/tools/guied/guied.cpp
	./engine/tools/materialeditor/ConsoleView.cpp
	./engine/tools/materialeditor/FindDialog.cpp
	./engine/tools/materialeditor/MaterialDef.cpp
	./engine/tools/materialeditor/MaterialDoc.cpp
	./engine/tools/materialeditor/MaterialDocManager.cpp
	./engine/tools/materialeditor/MaterialEditor.cpp
	./engine/tools/materialeditor/MaterialEditView.cpp
	./engine/tools/materialeditor/MaterialModifier.cpp
	./engine/tools/materialeditor/MaterialPreviewPropView.cpp
	./engine/tools/materialeditor/MaterialPreviewView.cpp
	./engine/tools/materialeditor/MaterialPropTreeView.cpp
	./engine/tools/materialeditor/MaterialTreeView.cpp
	./engine/tools/materialeditor/MaterialView.cpp
	./engine/tools/materialeditor/MEMainFrame.cpp
	./engine/tools/materialeditor/MEOptions.cpp
	./engine/tools/materialeditor/StageView.cpp
	./engine/tools/materialeditor/ToggleListView.cpp
	./engine/tools/pda/DialogPDAEditor.cpp
	./engine/tools/radiant/autocaulk.cpp
	./engine/tools/radiant/CameraTargetDlg.cpp
	./engine/tools/radiant/CamWnd.cpp
	./engine/tools/radiant/CapDialog.cpp
	./engine/tools/radiant/cmdlib.cpp
	./engine/tools/radiant/CommandsDlg.cpp
	./engine/tools/radiant/CommentsDlg.cpp
	./engine/tools/radiant/ConsoleDlg.cpp
	./engine/tools/radiant/CurveDlg.cpp
	./engine/tools/radiant/DialogInfo.cpp
	./engine/tools/radiant/DialogTextures.cpp
	./engine/tools/radiant/DialogThick.cpp
	./engine/tools/radiant/DlgCamera.cpp
	./engine/tools/radiant/DlgEvent.cpp
	./engine/tools/radiant/DRAG.cpp
	./engine/tools/radiant/ECLASS.cpp
	./engine/tools/radiant/EditorBrush.cpp
	./engine/tools/radiant/EditorBrushPrimit.cpp
	./engine/tools/radiant/EditorEntity.cpp
	./engine/tools/radiant/EditorMap.cpp
	./engine/tools/radiant/EditViewDlg.cpp
	./engine/tools/radiant/EntityDlg.cpp
	./engine/tools/radiant/EntKeyFindReplace.cpp
	./engine/tools/radiant/FindTextureDlg.cpp
	./engine/tools/radiant/GetString.cpp
	./engine/tools/radiant/GLWidget.cpp
	./engine/tools/radiant/InspectorDialog.cpp
	./engine/tools/radiant/LightDlg.cpp
	./engine/tools/radiant/CSG.cpp
	./engine/tools/radiant/MainFrm.cpp
	./engine/tools/radiant/MapInfo.cpp
	./engine/tools/radiant/MediaPreviewDlg.cpp
	./engine/tools/radiant/MRU.cpp
	./engine/tools/radiant/NewProjDlg.cpp
	./engine/tools/radiant/NewTexWnd.cpp
	./engine/tools/radiant/PARSE.cpp
	./engine/tools/radiant/PatchDensityDlg.cpp
	./engine/tools/radiant/PatchDialog.cpp
	./engine/tools/radiant/PMESH.cpp
	./engine/tools/radiant/PointFile.cpp
	./engine/tools/radiant/PrefsDlg.cpp
	./engine/tools/radiant/PreviewDlg.cpp
	./engine/tools/radiant/PropertyList.cpp
	./engine/tools/radiant/QE3.cpp
	./engine/tools/radiant/Radiant.cpp
	./engine/tools/radiant/RotateDlg.cpp
	./engine/tools/radiant/ScaleDialog.cpp
	./engine/tools/radiant/SELECT.cpp
	./engine/tools/radiant/splines.cpp
	./engine/tools/radiant/SurfaceDlg.cpp
	./engine/tools/radiant/TabsDlg.cpp
	./engine/tools/radiant/TearoffContainerWindow.cpp
	./engine/tools/radiant/TextureBar.cpp
	./engine/tools/radiant/Undo.cpp
	./engine/tools/radiant/VERTSEL.cpp
	./engine/tools/radiant/WaitDlg.cpp
	./engine/tools/radiant/WaveOpen.cpp
	./engine/tools/radiant/WIN_DLG.cpp
	./engine/tools/radiant/WIN_QE3.cpp
	./engine/tools/radiant/XYWnd.cpp
	./engine/tools/radiant/Z.cpp
	./engine/tools/radiant/ZClip.cpp
	./engine/tools/script/DialogScriptEditor.cpp
	./engine/tools/sound/DialogSound.cpp
	./engine/tools/sound/DialogSoundGroup.cpp
	./engine/tools/edit_public.h
	./engine/tools/tools_precompiled.h
	./engine/tools/af/DialogAF.h
	./engine/tools/af/DialogAFBody.h
	./engine/tools/af/DialogAFConstraint.h
	./engine/tools/af/DialogAFConstraintBallAndSocket.h
	./engine/tools/af/DialogAFConstraintFixed.h
	./engine/tools/af/DialogAFConstraintHinge.h
	./engine/tools/af/DialogAFConstraintSlider.h
	./engine/tools/af/DialogAFConstraintSpring.h
	./engine/tools/af/DialogAFConstraintUniversal.h
	./engine/tools/af/DialogAFName.h
	./engine/tools/af/DialogAFProperties.h
	./engine/tools/af/DialogAFView.h
	./engine/tools/comafx/CDIB.h
	./engine/tools/comafx/CPathTreeCtrl.h
	./engine/tools/comafx/CSyntaxRichEditCtrl.h
	./engine/tools/comafx/DialogColorPicker.h
	./engine/tools/comafx/DialogGoToLine.h
	./engine/tools/comafx/DialogName.h
	./engine/tools/comafx/StdAfx.h
	./engine/tools/comafx/VectorCtl.h
	./engine/tools/common/ColorButton.h
	./engine/tools/common/DialogHelpers.h
	./engine/tools/common/MaskEdit.h
	./engine/tools/common/OpenFileDialog.h
	./engine/tools/common/PropertyGrid.h
	./engine/tools/common/RegistryOptions.h
	./engine/tools/common/RenderBumpFlatDialog.h
	./engine/tools/common/RollupPanel.h
	./engine/tools/common/SpinButton.h
	./engine/tools/common/PropTree/PropTree.h
	./engine/tools/common/PropTree/PropTreeInfo.h
	./engine/tools/common/PropTree/PropTreeItem.h
	./engine/tools/common/PropTree/PropTreeItemButton.h
	./engine/tools/common/PropTree/PropTreeItemCheck.h
	./engine/tools/common/PropTree/PropTreeItemColor.h
	./engine/tools/common/PropTree/PropTreeItemCombo.h
	./engine/tools/common/PropTree/PropTreeItemEdit.h
	./engine/tools/common/PropTree/PropTreeItemEditButton.h
	./engine/tools/common/PropTree/PropTreeItemFileEdit.h
	./engine/tools/common/PropTree/PropTreeItemStatic.h
	./engine/tools/common/PropTree/PropTreeList.h
	./engine/tools/common/PropTree/PropTreeView.h
	./engine/tools/compilers/compiler_public.h
	./engine/tools/compilers/dmap/dmap.h
	./engine/tools/compilers/megagen/MegaGen.h
	./engine/tools/compilers/megalight/MegaLight_file.h
	./engine/tools/compilers/navmesh/navmeshbuild.cpp
	./engine/tools/debugger/DebuggerApp.h
	./engine/tools/debugger/DebuggerBreakpoint.h
	./engine/tools/debugger/DebuggerClient.h
	./engine/tools/debugger/DebuggerFindDlg.h
	./engine/tools/debugger/DebuggerMessages.h
	./engine/tools/debugger/DebuggerQuickWatchDlg.h
	./engine/tools/debugger/DebuggerScript.h
	./engine/tools/debugger/DebuggerServer.h
	./engine/tools/debugger/DebuggerWindow.h
	./engine/tools/decl/DialogDeclBrowser.h
	./engine/tools/decl/DialogDeclEditor.h
	./engine/tools/decl/DialogDeclNew.h
	./engine/tools/decl/DialogEntityDefEditor.h
	./engine/tools/guied/GEApp.h
	./engine/tools/guied/GEDeleteModifier.h
	./engine/tools/guied/GEHideModifier.h
	./engine/tools/guied/GEInsertModifier.h
	./engine/tools/guied/GEItemPropsDlg.h
	./engine/tools/guied/GEItemScriptsDlg.h
	./engine/tools/guied/GEKeyValueModifier.h
	./engine/tools/guied/GEModifier.h
	./engine/tools/guied/GEModifierGroup.h
	./engine/tools/guied/GEModifierStack.h
	./engine/tools/guied/GEMoveModifier.h
	./engine/tools/guied/GENavigator.h
	./engine/tools/guied/GEOptions.h
	./engine/tools/guied/GEOptionsDlg.h
	./engine/tools/guied/GEProperties.h
	./engine/tools/guied/GEPropertyPage.h
	./engine/tools/guied/GESelectionMgr.h
	./engine/tools/guied/GESizeModifier.h
	./engine/tools/guied/GEStateModifier.h
	./engine/tools/guied/GEStatusBar.h
	./engine/tools/guied/GETransformer.h
	./engine/tools/guied/GEViewer.h
	./engine/tools/guied/GEWindowWrapper.h
	./engine/tools/guied/GEWorkspace.h
	./engine/tools/guied/GEZOrderModifier.h
	./engine/tools/Help/default.htm
	./engine/tools/Help/MT_help.htm
	./engine/tools/Help/MVH_Controls.htm
	./engine/tools/Help/MVH_Issues.htm
	./engine/tools/Help/MVH_Misc.htm
	./engine/tools/Help/MVH_Mouse.htm
	./engine/tools/Help/MVH_Overview.htm
	./engine/tools/Help/Tools.hhc
	./engine/tools/Help/Tools.hhk
	./engine/tools/Help/Tools.hhp
	./engine/tools/materialeditor/ConsoleView.h
	./engine/tools/materialeditor/FindDialog.h
	./engine/tools/materialeditor/MaterialDef.h
	./engine/tools/materialeditor/MaterialDoc.h
	./engine/tools/materialeditor/MaterialDocManager.h
	./engine/tools/materialeditor/MaterialEditor.h
	./engine/tools/materialeditor/MaterialEditView.h
	./engine/tools/materialeditor/MaterialModifier.h
	./engine/tools/materialeditor/MaterialPreviewPropView.h
	./engine/tools/materialeditor/MaterialPreviewView.h
	./engine/tools/materialeditor/MaterialPropTreeView.h
	./engine/tools/materialeditor/MaterialTreeView.h
	./engine/tools/materialeditor/MaterialView.h
	./engine/tools/materialeditor/MEMainFrame.h
	./engine/tools/materialeditor/MEOptions.h
	./engine/tools/materialeditor/StageView.h
	./engine/tools/materialeditor/ToggleListView.h
	./engine/tools/pda/DialogPDAEditor.h
	./engine/tools/radiant/autocaulk.h
	./engine/tools/radiant/CameraTargetDlg.h
	./engine/tools/radiant/CamWnd.h
	./engine/tools/radiant/CapDialog.h
	./engine/tools/radiant/cmdlib.h
	./engine/tools/radiant/CommandsDlg.h
	./engine/tools/radiant/CommentsDlg.h
	./engine/tools/radiant/ConsoleDlg.h
	./engine/tools/radiant/CurveDlg.h
	./engine/tools/radiant/DialogInfo.h
	./engine/tools/radiant/DialogTextures.h
	./engine/tools/radiant/DialogThick.h
	./engine/tools/radiant/DlgCamera.h
	./engine/tools/radiant/DlgEvent.h
	./engine/tools/radiant/EditorBrush.h
	./engine/tools/radiant/EditorEntity.h
	./engine/tools/radiant/EditorMap.h
	./engine/tools/radiant/EditViewDlg.h
	./engine/tools/radiant/EntityDlg.h
	./engine/tools/radiant/EntKeyFindReplace.h
	./engine/tools/radiant/FindTextureDlg.h
	./engine/tools/radiant/GetString.h
	./engine/tools/radiant/GLWidget.h
	./engine/tools/radiant/InspectorDialog.h
	./engine/tools/radiant/LightDlg.h
	./engine/tools/radiant/MainFrm.h
	./engine/tools/radiant/MapInfo.h
	./engine/tools/radiant/MediaPreviewDlg.h
	./engine/tools/radiant/MRU.H
	./engine/tools/radiant/NewProjDlg.h
	./engine/tools/radiant/NewTexWnd.h
	./engine/tools/radiant/PARSE.H
	./engine/tools/radiant/PatchDensityDlg.h
	./engine/tools/radiant/PatchDialog.h
	./engine/tools/radiant/PMESH.H
	./engine/tools/radiant/PrefsDlg.h
	./engine/tools/radiant/PreviewDlg.h
	./engine/tools/radiant/PropertyList.h
	./engine/tools/radiant/QE3.H
	./engine/tools/radiant/QEDEFS.H
	./engine/tools/radiant/QERTYPES.H
	./engine/tools/radiant/Radiant.h
	./engine/tools/radiant/RotateDlg.h
	./engine/tools/radiant/ScaleDialog.h
	./engine/tools/radiant/SELECT.H
	./engine/tools/radiant/splines.h
	./engine/tools/radiant/SurfaceDlg.h
	./engine/tools/radiant/TabsDlg.h
	./engine/tools/radiant/TearoffContainerWindow.h
	./engine/tools/radiant/TextureBar.h
	./engine/tools/radiant/Textures.h
	./engine/tools/radiant/Undo.h
	./engine/tools/radiant/WaitDlg.h
	./engine/tools/radiant/WaveOpen.h
	./engine/tools/radiant/XYWnd.h
	./engine/tools/radiant/Z.H
	./engine/tools/radiant/ZClip.h
	./engine/tools/script/DialogScriptEditor.h
	./engine/tools/sound/DialogSound.h
	./engine/tools/sound/DialogSoundGroup.h
	./engine/tools/guis/FrameRateGui.cpp
)

# Add radiant.net
#add_library(RadiantDotNet SHARED ${src_radiant_net})
#set_property(TARGET RadiantDotNet PROPERTY VS_DOTNET_TARGET_FRAMEWORK_VERSION "v4.6.1")
#set(CMAKE_CSharp_FLAGS "/langversion:latest")
#set_property(TARGET RadiantDotNet PROPERTY VS_DOTNET_REFERENCES
#    "Microsoft.CSharp"
#    "System"
#    "System.Core"
#    "System.Data"
#    "System.Deployment"
#    "System.Drawing"
#    "System.Net.Http"
#    "System.Xml"
#)

# Add tools library
add_library(Tools STATIC ${src_tools})
add_precompiled_header( Tools tools_precompiled.h  SOURCE_CXX ./engine/tools/tools_precompiled.cpp )
set_target_properties(Tools PROPERTIES LINK_FLAGS "/PDB:\"Tools.pdb\"")
target_include_directories(Tools PRIVATE ./engine/external/Recast/include)


# MayaImport
if(EXISTS "C:\\Program Files\\Autodesk\\Maya2019\\include\\qt-5.6.1_vc14-include.zip") 
	Message("Found Maya 2019 SDK...")
	add_library(mayaimport MODULE  ${src_maya_import} )
	target_compile_definitions(mayaimport PRIVATE MAYA_IMPORT=1)
	target_link_libraries(mayaimport idLib "foundation.lib" "OpenMaya.lib" "OpenMayaAnim.lib")
	add_precompiled_header( mayaimport maya_precompiled.h  SOURCE_CXX ./engine/MayaImport/maya_precompiled.cpp )
	set_target_properties(mayaimport PROPERTIES OUTPUT_NAME "MayaImport2019x64" LINK_FLAGS "/STACK:36777216,36777216 /PDB:\"MayaImport.pdb\" /DEF:${CMAKE_CURRENT_SOURCE_DIR}/engine/MayaImport/mayaimport.def")
	# MayaImport 2019 Maya Folders
	target_include_directories(mayaimport PUBLIC "C:\\Program Files\\Autodesk\\Maya2019\\include")
	target_link_directories(mayaimport PUBLIC "C:\\Program Files\\Autodesk\\Maya2019\\lib")
else()
	Message("Maya 2019 SDK not found, not building MayaImport...")
endif()
